name: paymob_pakistan
description: Easily accept payments through Online Cards in your Flutter app with Paymob.
version: 1.0.1
homepage: https://github.com/arshmancodes/paymob_pakistan
repository: https://github.com/arshmancodes/paymob_pakistan

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  dio: ^5.2.1+1
  webview_flutter: ^4.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2